import os

files = [
    "app.py",
    "requirements.txt",
    "Dockerfile"
]

for file in files:
    if not os.path.exists(file):
        raise Exception(f"{file} Missing")

print("Validation Successful")
